version: "3"
services:
  app:
    build: .
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app # ボリュームマウント
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - data-dev:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d # test_db.sqlでテスト用のデータベースを作成する
    container_name: db-container
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/swagger/swagger.yaml
    ports:
      - "8081:8080"
    volumes:
      - ./swagger:/swagger

volumes:
  data-dev:
    driver: local
